config/routes.rb
Firehose3::Application.routes.draw do

  root :to => 'staticpages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
   attr_accessible :hour, :emotion, :learned, :image

   mount_uploader :image, PictureUploader
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
def new  
@pic = Pic.new

end


def create 
	@pic = Pic.create(params[:pic])
	redirect_to pics_path
end

def index
	@pics = Pic.all
end


def show
end

def destroy 
end

def edit 
end

def update 
end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	
	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firehose3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class="navbar navbarwarning btn--inverse">
   <div class="navbar">
	
    
    <div class="navbar-inner">
	    <div class="container">
	     
	    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    </a>
	     
	    <!-- Be sure to leave the brand out there if you want it shown -->
	    
	     	<%= link_to('Matts Brand New App', root_path, :class =>'brand' ) %>


	    <!-- Everything you want hidden at 940px or less, place within here -->
		    <div class="nav-collapse collapse">
		    <!-- .nav, .navbar-search, .navbar-form, etc -->
		 <ul class="nav">
		 	
		 		<%= link_to('My app', pics_path, :class => 'btn btn-warning') %>


 				<%= link_to 'New Pic', new_pic_path, :class => 'btn btn-warning' %>

						 		
		 </ul>

		    </div>
	      </div>
    </div>
</div>
</div>
<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
	<h1 class = "custom-pic-header">Here are all the pictures</h1>

	<% @pics.each do |pic| %>
    <div class="span3">

	    <div class="boxy">

			<h4>Hour:</h4> <em><%= pic.hour %></em>
    		<p />
    		<%= image_tag pic.image %>

			<h5>Emotion:</h5> <em><%= pic.emotion %></em>
    		   		
			<h5>Learned:</h5><em> <%= pic.learned %></em>
			
    		</P>
	
    	</div>
	</div>
    
    <% end %>
    <br />
</div>

app/views/pics/new.html.erb
<div class="span6 offset3 text-center">
	<h1 class="custom-pic-header">Add a new picture</h1>
	<div class="boxy text-center">

	<%= simple_form_for @pic do |f| %> 

   		<%= f.input :hour %>
   		<%= f.input :image, :as => :file %>
   		<%= f.input :emotion %>
   		<%= f.input :learned %>
   		<%= submit_tag "Submit"%>

	<% end %>
	</div>
</div>

app/views/staticpages/index.html.erb
<div class="span6 offset3">

    <div class="boxy" id="mainbox">

         <h1 class="custom-font">Hi, I'm Matt</h1>

<p>Upload your own picture ... and <em>nothing</em> else happens!
	<p>

<%= link_to('Check out my App', '#', :class => 'btn btn-success btn-large') %>


</div>
</div>